### ISSUE TITLE
Paths in S3 should be lowercase

### ISSUE THREAD

**Issue by alemf90** [helpshift/pypiprivate#3]
Hello,

First of all I would like to thank you for this great project.
The latest version has a bug, which can be easily fixed.

If the following command is used:
 pypi-private -c .pypi-private.cfg -v publish -d repo MySamplePackage 2.4.1

The tool will upload the file in  S3 with this path:
/simple/MySamplePackage/MySamplePackage-2.4.1.tar.gz

This is an issue because when you use "pip install MySamplePackage", pip will look for:
https://s3bucketurl.com/simple/mysimplepackage/ <-- which will fail.

This issue can be easily fixed by converting the strings in lowercase in the following line in storage.py
    def prefixed_path(self, path):
        parts = []
        if self.prefix:
            parts.append(self.prefix)
        if path != '.':
            parts.append(path.lower())
        return self.join_path(*parts)

Simply adding lower() would do the trick.

Reference:
Normalized names section in https://www.python.org/dev/peps/pep-0503/#id4

**Comment by naiquevin** [comment]
Thanks for reporting the bug. I'll push a fix shortly.
